### ISSUE TITLE
getProperties() causes position properties to separate.

### ISSUE THREAD

**Issue by foughtthelaw** [aenhancers/aequery#65]
I'm working on a script that searches all properties in the active comp using the following line
`var props = aeq.getProperties(aeq.getLayers(aeq.getActiveComp()))`

When that gets run ALL position properties get _Seperate Dimensions_ enabled. This would be fine if it didn't also obliterate any easing on existing keyframes. Not sure if this is a limitation of AE or something happening in AEQ but at least worth reporting.

**Comment by runegan** [comment]
It's defined to do this by default, it's possible to pass options to skip
this, but I agree that it is a weird default.

https://github.com/aenhancers/aequery/blob/57779bb63baeca1edca7c316527d1e47060df80e/lib/dom.js#L235

**Comment by foughtthelaw** [comment]
Actually [this line](https://github.com/aenhancers/aequery/blob/57779bb63baeca1edca7c316527d1e47060df80e/lib/dom.js#L267) makes it look like it's not supposed to be the default, so that makes me suspect it actually is a bug.
